# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: 
      - release

jobs:

  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 9

      - uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile && pnpm build
      
      - name: Publish package
        run: |
          cd ./packages/thgraph/
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org/
      
      - name: Get package version
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version
        with: 
          path: "./packages/thgraph/package.json"

      - name: Create a tag
        uses: negz/create-tag@v1
        with:
            version: v${{ steps.package-version.outputs.version }}
            message: "Release v${{ steps.package-version.outputs.version }}"
            token: ${{ secrets.GITHUB_TOKEN }}
