name: Deploy docs
on:
  push:
    branches:
      - main
    
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.27.1
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: "pnpm"

      - name: Install
        run: pnpm --filter=docs install
      - name: Build
        run:  pnpm --filter=docs docs:build
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: packages/docs/.vitepress/dist
      - name: Deploy build page
        id: deployment
        uses: actions/deploy-pages@v1
